const legacyFavorites=JSON.parse(localStorage.getItem('rsr-favorites')||'[]');
const state={data:[],q:'',category:'',subPath:[],shopFavorites:new Set(JSON.parse(localStorage.getItem('rsr-shop-favorites')||JSON.stringify(legacyFavorites))),menuFavorites:new Set(JSON.parse(localStorage.getItem('rsr-menu-favorites')||'[]')),shopFavoritesOnly:false,menuFavoritesOnly:false,position:null,sort:'name',map:null,mapShop:null,userLayer:null};
const $=s=>document.querySelector(s);const categories=['麺','ご飯','カレー','肉','海鮮','軽食','スイーツ','朝食','飲み物'];
const hierarchy={
  '麺':[{name:'ラーメン',match:/ラーメン|らーめん|らぁ麺|油そば|まぜそば|担々麺/,children:[{name:'スープあり',match:/ラーメン|らーめん|らぁ麺|担々麺/},{name:'汁なし',match:/油そば|まぜそば|汁なし/,children:[{name:'油そば',match:/油そば/},{name:'まぜそば',match:/まぜそば/}]}]},{name:'うどん',match:/うどん/},{name:'そば',match:/そば/},{name:'焼きそば',match:/焼きそば/},{name:'パスタ',match:/パスタ|スパゲッティ/},{name:'その他の麺',match:/麺/}],
  'ご飯':[{name:'丼',match:/丼|ロコモコ/},{name:'おにぎり',match:/おにぎり/},{name:'炊き込みご飯',match:/炊き込み|たこ飯|ごはん|飯/},{name:'その他',match:/ライス|ご飯/}],
  'カレー':[{name:'欧風',match:/欧風/},{name:'スパイス',match:/スパイス|キーマ/},{name:'スープカレー',match:/スープカレー/},{name:'その他',match:/カレー|イシカリー/}],
  '肉':[{name:'牛',match:/牛|ビーフ|カルビ/},{name:'豚',match:/豚|ポーク|チャーシュー/},{name:'鶏',match:/鶏|チキン|ザンギ|唐揚/},{name:'ジンギスカン',match:/ジンギスカン|ラム/},{name:'ソーセージ',match:/ソーセージ|フランク/},{name:'その他',match:/肉|ホルモン/}],
  '海鮮':[{name:'たこ・いか',match:/たこ|タコ|いか|イカ/},{name:'えび・かに',match:/えび|エビ|かに|カニ|蟹/},{name:'魚',match:/鮭|サーモン|まぐろ|マグロ|魚/},{name:'貝',match:/帆立|ホタテ|貝/},{name:'海鮮丼',match:/海鮮丼/}],
  '軽食':[{name:'ザンギ・唐揚げ',match:/ザンギ|唐揚|チキン/},{name:'ポテト',match:/ポテト|いも/},{name:'たこ焼き',match:/たこ焼き/},{name:'餃子',match:/餃子/},{name:'ホットドッグ',match:/ホットドッグ|ホットドック|フランク/},{name:'バーガー',match:/バーガー/}],
  'スイーツ':[{name:'アイス',match:/アイス|ジェラート/},{name:'ソフトクリーム',match:/ソフトクリーム/},{name:'かき氷',match:/かき氷/},{name:'フルーツ',match:/フルーツ|いちご|メロン/},{name:'ケーキ・焼菓子',match:/ケーキ|クッキー|ドーナツ|プリン/}],
  '飲み物':[{name:'アルコール',match:/ビール|ハイボール|サワー|チューハイ|日本酒|焼酎|カクテル|ワイン|酒/,children:[{name:'ビール',match:/ビール/},{name:'ハイボール',match:/ハイボール/},{name:'サワー・チューハイ',match:/サワー|チューハイ/},{name:'日本酒・焼酎',match:/日本酒|焼酎/},{name:'カクテル・ワイン',match:/カクテル|ワイン/}]},{name:'ソフトドリンク',match:/ジュース|ソーダ|ドリンク|茶|水|ポカリ|レモネード/},{name:'カフェ',match:/コーヒー|ラテ|カフェ|エスプレッソ/}]
};
const params=new URLSearchParams(location.search);state.q=params.get('q')||'';state.category=params.get('category')||'';state.shopFavoritesOnly=['shop','both'].includes(params.get('favorites'));state.menuFavoritesOnly=['menu','both'].includes(params.get('favorites'));
$('#search').value=state.q;$('#shop-favorites-only').checked=state.shopFavoritesOnly;$('#menu-favorites-only').checked=state.menuFavoritesOnly;

function normalize(s=''){return s.normalize('NFKC').toLowerCase().replace(/[ァ-ン]/g,c=>String.fromCharCode(c.charCodeAt(0)-0x60)).replace(/\s/g,'')}
function distance(a,b){const r=6371000,p=Math.PI/180,dLat=(b.lat-a.lat)*p,dLng=(b.lng-a.lng)*p;const x=Math.sin(dLat/2)**2+Math.cos(a.lat*p)*Math.cos(b.lat*p)*Math.sin(dLng/2)**2;return 2*r*Math.asin(Math.sqrt(x))}
function formatDistance(m){if(m==null)return '距離情報準備中';if(m<1000)return `出店エリアまで 約${Math.round(m/10)*10}m（概算）`;return `出店エリアまで 約${(m/1000).toFixed(1)}km（概算）`}
function updateUrl(){const p=new URLSearchParams();if(state.q)p.set('q',state.q);if(state.category)p.set('category',state.category);if(state.shopFavoritesOnly||state.menuFavoritesOnly)p.set('favorites',state.shopFavoritesOnly&&state.menuFavoritesOnly?'both':state.shopFavoritesOnly?'shop':'menu');history.replaceState(null,'',`${location.pathname}${p.size?'?'+p:''}`)}
function renderCategories(){const root=$('#categories');root.innerHTML='';categories.forEach(c=>{const b=document.createElement('button');b.className='category'+(state.category===c?' selected':'');b.textContent=c;b.onclick=()=>{state.category=state.category===c?'':c;state.subPath=[];render();};root.append(b)});renderSubs()}
function currentNodes(){let nodes=hierarchy[state.category]||[];for(const selected of state.subPath){const node=nodes.find(n=>n.name===selected);nodes=node?.children||[]}return nodes}
function renderSubs(){const root=$('#subfilters');const nodes=currentNodes();if(!state.category||(!nodes.length&&!state.subPath.length)){root.hidden=true;return}root.hidden=false;const crumbs=[state.category,...state.subPath].map((x,i)=>`<button data-level="${i-1}">${x}</button>`).join('<span>›</span>');const choices=nodes.map(n=>`<button data-name="${n.name}">${n.name}</button>`).join('');root.innerHTML=`<div class="breadcrumbs">${crumbs}</div><div class="subchoices"><button class="selected">この階層をすべて</button>${choices}</div>`;root.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>{const level=Number(b.dataset.level);state.subPath=level<0?[]:state.subPath.slice(0,level+1);renderSubs();renderResults()});root.querySelectorAll('[data-name]').forEach(b=>b.onclick=()=>{state.subPath.push(b.dataset.name);renderSubs();renderResults()})}
function selectedNode(){let nodes=hierarchy[state.category]||[],node=null;for(const name of state.subPath){node=nodes.find(n=>n.name===name);nodes=node?.children||[]}return node}
function matches(shop,menu){const hay=normalize([shop.name,shop.area,menu.name,...menu.categories,...menu.tags].join(' '));const node=selectedNode();const favoriteMatch=(!state.shopFavoritesOnly&&!state.menuFavoritesOnly)||(state.shopFavoritesOnly&&state.shopFavorites.has(shop.id))||(state.menuFavoritesOnly&&state.menuFavorites.has(menu.id));return(!state.q||hay.includes(normalize(state.q)))&&(!state.category||menu.categories.includes(state.category))&&(!node||node.match.test(menu.name))&&favoriteMatch}
function rows(){let items=state.data.flatMap(shop=>shop.menus.filter(m=>matches(shop,m)).map(menu=>({shop,menu,dist:state.position&&shop.lat!=null?distance(state.position,shop):null})));items.sort(state.sort==='distance'?(a,b)=>(a.dist??Infinity)-(b.dist??Infinity)||(a.shop.name.localeCompare(b.shop.name,'ja')):(a,b)=>a.shop.name.localeCompare(b.shop.name,'ja')||b.menu.special-a.menu.special);return items}
function renderResults(){updateUrl();const items=rows();$('#result-count').textContent=items.length;$('#status').hidden=true;const root=$('#cards');root.innerHTML='';if(!items.length){root.innerHTML='<div class="empty"><b>見つかりませんでした</b><br>条件を減らすか、別の言葉で試してください。</div>';return}const tpl=$('#card-template');items.forEach(({shop,menu,dist})=>{const card=tpl.content.firstElementChild.cloneNode(true);card.classList.toggle('is-special',menu.special);const img=card.querySelector('.photo');img.src=shop.imageUrl;img.alt=`${shop.name} ${menu.name}`;img.onerror=()=>img.remove();card.querySelector('.area').textContent=shop.area;card.querySelector('.menu-name').textContent=menu.name;card.querySelector('.shop-name').textContent=shop.name;card.querySelector('.chips').innerHTML=[...menu.categories,...menu.tags].map(x=>`<span class="chip">${x}</span>`).join('');card.querySelector('.distance').textContent=formatDistance(dist);card.querySelector('.card-main').onclick=()=>openDetail(shop,menu,dist);const shopFav=card.querySelector('.shop-favorite'),menuFav=card.querySelector('.menu-favorite');setFavoriteButton(shopFav,state.shopFavorites.has(shop.id),'店');setFavoriteButton(menuFav,state.menuFavorites.has(menu.id),'飯');shopFav.onclick=()=>toggleShopFavorite(shop.id);menuFav.onclick=()=>toggleMenuFavorite(menu.id);root.append(card)})}
function setFavoriteButton(button,on,label){button.classList.toggle('on',on);button.textContent=on?`${label}♥`:`${label}♡`;button.setAttribute('aria-label',`${label==='店'?'お店':'メニュー'}をお気に入り${on?'から削除':'に追加'}`)}
function toggleShopFavorite(id){state.shopFavorites.has(id)?state.shopFavorites.delete(id):state.shopFavorites.add(id);localStorage.setItem('rsr-shop-favorites',JSON.stringify([...state.shopFavorites]));renderResults()}
function toggleMenuFavorite(id){state.menuFavorites.has(id)?state.menuFavorites.delete(id):state.menuFavorites.add(id);localStorage.setItem('rsr-menu-favorites',JSON.stringify([...state.menuFavorites]));renderResults()}
function openDetail(shop,menu,dist){const menus=shop.menus.map(m=>`<li>${m.special?'<b>RSRスペシャル：</b>':''}${m.name}</li>`).join('');$('#detail-content').innerHTML=`<button class="detail-close" aria-label="閉じる">×</button><img class="detail-image" src="${shop.imageUrl}" alt="${shop.name}"><div class="detail-inner"><div class="area">${shop.area}</div><h2>${shop.name}</h2><button class="place-button" type="button">⌖ ${shop.area}を地図で見る</button><div class="distance">${formatDistance(dist)}</div>${shop.coordinateType==='estimated-area-center'?'<p class="coordinate-note">公式会場マップを基準にした出店エリア中心までの概算です。店舗テント個別の測量座標ではありません。</p>':''}<h3>選んだメニュー</h3><p><b>${menu.name}</b></p><div class="chips">${[...menu.categories,...menu.tags].map(x=>`<span class="chip">${x}</span>`).join('')}</div><div class="detail-favorite-actions"><button class="detail-shop-fav">${state.shopFavorites.has(shop.id)?'店♥ お店お気に入り済み':'店♡ お店をお気に入り'}</button><button class="detail-menu-fav">${state.menuFavorites.has(menu.id)?'飯♥ メニューお気に入り済み':'飯♡ メニューをお気に入り'}</button></div><h3>全メニュー</h3><ul class="menu-list">${menus}</ul>${shop.description?`<h3>店舗PR</h3><p>${shop.description}</p>`:''}<div class="detail-actions"><a href="${shop.sourceUrl}" target="_blank" rel="noopener">公式情報を見る ↗</a></div></div>`;$('#detail-content .detail-close').onclick=()=>$('#detail').close();$('#detail-content .place-button').onclick=()=>{$('#detail').close();openMap(shop)};$('#detail-content .detail-shop-fav').onclick=()=>{toggleShopFavorite(shop.id);$('#detail').close()};$('#detail-content .detail-menu-fav').onclick=()=>{toggleMenuFavorite(menu.id);$('#detail').close()};$('#detail').showModal()}
function locationIcon(kind){return L.divIcon({className:`map-pin ${kind}`,html:`<span><b>${kind==='shop'?'店':'●'}</b></span>`,iconSize:[34,42],iconAnchor:[17,39]})}
function addUserToMap(){if(!state.map||!state.position)return;if(state.userLayer)state.userLayer.remove();state.userLayer=L.layerGroup([L.marker([state.position.lat,state.position.lng],{icon:locationIcon('user'),title:'現在地'}).bindPopup('現在地'),L.circle([state.position.lat,state.position.lng],{radius:state.position.accuracy||20,color:'#2276d2',fillColor:'#5aa8ff',fillOpacity:.12,weight:1})]).addTo(state.map);const bounds=L.latLngBounds([[state.mapShop.lat,state.mapShop.lng],[state.position.lat,state.position.lng]]);state.map.fitBounds(bounds.pad(.45),{maxZoom:18})}
function openMap(shop){state.mapShop=shop;$('#map-shop-name').textContent=shop.name;$('#map-area-name').textContent=shop.area;$('#map-dialog').showModal();setTimeout(()=>{if(state.map)state.map.remove();state.map=L.map('shop-map',{zoomControl:true}).setView([shop.lat,shop.lng],17);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).addTo(state.map);L.marker([shop.lat,shop.lng],{icon:locationIcon('shop'),title:shop.area}).addTo(state.map).bindPopup(`<b>${shop.area}</b><br>${shop.name}<br><small>推定エリア中心</small>`).openPopup();addUserToMap();},100)}
function locate(onSuccess){if(!navigator.geolocation){alert('この端末では位置情報を利用できません。');return}$('#locate').textContent='位置を確認中…';$('#map-locate').textContent='位置を確認中…';navigator.geolocation.getCurrentPosition(p=>{state.position={lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy};$('#locate').textContent='✓ 現在地を取得済み';$('#map-locate').textContent='✓ 現在地を表示中';state.sort='distance';$('#sort').value='distance';renderResults();addUserToMap();if(typeof onSuccess==='function')onSuccess()},()=>{$('#locate').textContent='◎ 現在地を使う';$('#map-locate').textContent='◎ 現在地も表示';alert('位置情報を取得できませんでした。検索と地図はそのまま利用できます。')},{enableHighAccuracy:true,timeout:10000,maximumAge:60000})}
function render(){renderCategories();renderResults()}
$('#search').oninput=e=>{state.q=e.target.value;renderResults()};$('#clear-search').onclick=()=>{$('#search').value='';state.q='';renderResults();$('#search').focus()};$('#shop-favorites-only').onchange=e=>{state.shopFavoritesOnly=e.target.checked;renderResults()};$('#menu-favorites-only').onchange=e=>{state.menuFavoritesOnly=e.target.checked;renderResults()};$('#sort').onchange=e=>{state.sort=e.target.value;renderResults()};$('#locate').onclick=()=>locate();$('#map-locate').onclick=()=>locate();$('#detail').onclick=e=>{if(e.target===$('#detail'))$('#detail').close()};$('.map-close').onclick=()=>$('#map-dialog').close();$('#map-dialog').onclick=e=>{if(e.target===$('#map-dialog'))$('#map-dialog').close()};$('#map-dialog').addEventListener('close',()=>{if(state.map){state.map.remove();state.map=null}state.userLayer=null});
document.querySelectorAll('.bottom-nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.bottom-nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(b.dataset.action==='search'){state.shopFavoritesOnly=false;state.menuFavoritesOnly=false;$('#shop-favorites-only').checked=false;$('#menu-favorites-only').checked=false;scrollTo({top:0,behavior:'smooth'});renderResults()}if(b.dataset.action==='favorites'){state.shopFavoritesOnly=true;state.menuFavoritesOnly=true;$('#shop-favorites-only').checked=true;$('#menu-favorites-only').checked=true;renderResults();scrollTo({top:document.querySelector('.results').offsetTop,behavior:'smooth'})}if(b.dataset.action==='near')locate()});
fetch('data/shops.json').then(r=>{if(!r.ok)throw Error(r.status);return r.json()}).then(d=>{state.data=d.shops;render()}).catch(()=>{$('#status').textContent='データを読み込めませんでした。通信環境を確認して再読み込みしてください。'});
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('sw.js'));
