const legacyFavorites=JSON.parse(localStorage.getItem('rsr-favorites')||'[]');
const state={data:[],q:'',category:'',area:'',subPath:[],shopFavorites:new Set(JSON.parse(localStorage.getItem('rsr-shop-favorites')||JSON.stringify(legacyFavorites))),menuFavorites:new Set(JSON.parse(localStorage.getItem('rsr-menu-favorites')||'[]')),shopFavoritesOnly:false,menuFavoritesOnly:false,position:null,sort:'name',map:null,mapShop:null,userLayer:null};
const $=s=>document.querySelector(s);const categories=['麺','ご飯','カレー','肉','海鮮','軽食','スイーツ','朝食','飲み物'];
const venueMap={width:2072,height:1910,x:[514.8338934897748,87514.69744314403,-12385714.221532168],y:[151476.22812558583,-11664.858619111323,-4891383.699124284]};
const venueAreaPoints={'Forest Restaurant':{x:547,y:283},'Water Station':{x:1805,y:499},'Oyahuru Restaurant & Decorate':{x:1198,y:607},'オフィシャルダイニング チュプ':{x:1267,y:626},'Bitoi Restaurant':{x:829,y:762},'Hachiman Restaurant & Decorate':{x:941,y:828},'PROVO FOOD & BAR':{x:1197,y:861},'Hamanasu Restaurant':{x:1267,y:872},'Tarukawa Restaurant':{x:1888,y:759},'Matsuri Café':{x:1642,y:1041},'Bannaguro Restaurant with 石狩市場×小樽横丁':{x:1718,y:1027},'greentope':{x:869,y:1248}};
const hierarchy={
  '麺':[{name:'ラーメン',match:/ラーメン|らーめん|らぁ麺|油そば|まぜそば|担々麺/,children:[{name:'スープあり',match:/ラーメン|らーめん|らぁ麺|担々麺/},{name:'汁なし',match:/油そば|まぜそば|汁なし/,children:[{name:'油そば',match:/油そば/},{name:'まぜそば',match:/まぜそば/}]}]},{name:'うどん',match:/うどん/},{name:'そば',match:/そば/},{name:'焼きそば',match:/焼きそば/},{name:'パスタ',match:/パスタ|スパゲッティ/},{name:'その他の麺',match:/麺/}],
  'ご飯':[{name:'丼',match:/丼|ロコモコ/},{name:'おにぎり',match:/おにぎり/},{name:'炊き込みご飯',match:/炊き込み|たこ飯|ごはん|飯/},{name:'その他',match:/ライス|ご飯/}],
  'カレー':[{name:'欧風',match:/欧風/},{name:'スパイス',match:/スパイス|キーマ/},{name:'スープカレー',match:/スープカレー/},{name:'その他',match:/カレー|イシカリー/}],
  '肉':[{name:'牛',match:/牛|ビーフ|カルビ/},{name:'豚',match:/豚|ポーク|チャーシュー/},{name:'鶏',match:/鶏|チキン|ザンギ|唐揚/},{name:'ジンギスカン',match:/ジンギスカン|ラム/},{name:'ソーセージ',match:/ソーセージ|フランク/},{name:'その他',match:/肉|ホルモン/}],
  '海鮮':[{name:'たこ・いか',match:/たこ|タコ|いか|イカ/},{name:'えび・かに',match:/えび|エビ|かに|カニ|蟹/},{name:'魚',match:/鮭|サーモン|まぐろ|マグロ|魚/},{name:'貝',match:/帆立|ホタテ|貝/},{name:'海鮮丼',match:/海鮮丼/}],
  '軽食':[{name:'ザンギ・唐揚げ',match:/ザンギ|唐揚|チキン/},{name:'ポテト',match:/ポテト|いも/},{name:'たこ焼き',match:/たこ焼き/},{name:'餃子',match:/餃子/},{name:'ホットドッグ',match:/ホットドッグ|ホットドック|フランク/},{name:'バーガー',match:/バーガー/}],
  'スイーツ':[{name:'アイス',match:/アイス|ジェラート/},{name:'ソフトクリーム',match:/ソフトクリーム/},{name:'かき氷',match:/かき氷/},{name:'フルーツ',match:/フルーツ|いちご|メロン/},{name:'ケーキ・焼菓子',match:/ケーキ|クッキー|ドーナツ|プリン/}],
  '飲み物':[{name:'アルコール',match:/ビール|ハイボール|サワー|チューハイ|日本酒|焼酎|カクテル|ワイン|酒/,children:[{name:'ビール',match:/ビール/},{name:'ハイボール',match:/ハイボール/},{name:'サワー・チューハイ',match:/サワー|チューハイ/},{name:'日本酒・焼酎',match:/日本酒|焼酎/},{name:'カクテル・ワイン',match:/カクテル|ワイン/}]},{name:'ソフトドリンク',match:/ジュース|ソーダ|ドリンク|茶|水|ポカリ|レモネード/},{name:'カフェ',match:/コーヒー|ラテ|カフェ|エスプレッソ/}]
};
const params=new URLSearchParams(location.search);state.q=params.get('q')||'';state.category=params.get('category')||'';state.area=params.get('area')||'';state.shopFavoritesOnly=['shop','both'].includes(params.get('favorites'));state.menuFavoritesOnly=['menu','both'].includes(params.get('favorites'));
$('#search').value=state.q;$('#shop-favorites-only').checked=state.shopFavoritesOnly;$('#menu-favorites-only').checked=state.menuFavoritesOnly;

function normalize(s=''){return s.normalize('NFKC').toLowerCase().replace(/[ァ-ン]/g,c=>String.fromCharCode(c.charCodeAt(0)-0x60)).replace(/\s/g,'')}
function distance(a,b){const r=6371000,p=Math.PI/180,dLat=(b.lat-a.lat)*p,dLng=(b.lng-a.lng)*p;const x=Math.sin(dLat/2)**2+Math.cos(a.lat*p)*Math.cos(b.lat*p)*Math.sin(dLng/2)**2;return 2*r*Math.asin(Math.sqrt(x))}
function formatDistance(m){if(m==null)return '距離情報準備中';if(m<1000)return `出店エリアまで 約${Math.round(m/10)*10}m（概算）`;return `出店エリアまで 約${(m/1000).toFixed(1)}km（概算）`}
function updateUrl(){const p=new URLSearchParams();if(state.q)p.set('q',state.q);if(state.category)p.set('category',state.category);if(state.area)p.set('area',state.area);if(state.shopFavoritesOnly||state.menuFavoritesOnly)p.set('favorites',state.shopFavoritesOnly&&state.menuFavoritesOnly?'both':state.shopFavoritesOnly?'shop':'menu');history.replaceState(null,'',`${location.pathname}${p.size?'?'+p:''}`)}
function renderAreas(){const select=$('#area-filter'),areas=[...new Set(state.data.map(shop=>shop.area))].sort((a,b)=>a.localeCompare(b,'ja'));select.innerHTML='<option value="">すべての出店エリア</option>'+areas.map(area=>`<option value="${area}">${area}</option>`).join('');select.value=state.area;if(state.area&&!areas.includes(state.area)){state.area='';select.value=''}}
function showNearestArea(){if(!state.position||!state.data.length)return;const user=toVenuePoint(state.position.lat,state.position.lng),areas=[...new Map(state.data.filter(shop=>shop.lat!=null).map(shop=>[shop.area,shop])).values()].map(shop=>{const point=venueAreaPoints[shop.area]||toVenuePoint(shop.lat,shop.lng);return{name:shop.area,meters:distance(state.position,shop),mapDistance:Math.hypot(point.x-user.x,point.y-user.y)}}).sort((a,b)=>a.mapDistance-b.mapDistance),nearest=areas[0];if(!nearest)return;$('#nearest-area-name').textContent=nearest.name;$('#nearest-area-distance').textContent=nearest.meters<1000?`約${Math.round(nearest.meters/10)*10}m`:`約${(nearest.meters/1000).toFixed(1)}km`;$('#nearest-area').hidden=false;$('#select-nearest-area').onclick=()=>{state.area=nearest.name;$('#area-filter').value=nearest.name;renderResults();document.querySelector('.results').scrollIntoView({behavior:'smooth',block:'start'})}}
function renderCategories(){const root=$('#categories');root.innerHTML='';categories.forEach(c=>{const b=document.createElement('button');b.className='category'+(state.category===c?' selected':'');b.textContent=c;b.onclick=()=>{state.category=state.category===c?'':c;state.subPath=[];render();};root.append(b)});renderSubs()}
function currentNodes(){let nodes=hierarchy[state.category]||[];for(const selected of state.subPath){const node=nodes.find(n=>n.name===selected);nodes=node?.children||[]}return nodes}
function renderSubs(){const root=$('#subfilters');const nodes=currentNodes();if(!state.category||(!nodes.length&&!state.subPath.length)){root.hidden=true;return}root.hidden=false;const crumbs=[state.category,...state.subPath].map((x,i)=>`<button data-level="${i-1}">${x}</button>`).join('<span>›</span>');const choices=nodes.map(n=>`<button data-name="${n.name}">${n.name}</button>`).join('');root.innerHTML=`<div class="breadcrumbs">${crumbs}</div><div class="subchoices"><button class="selected">この階層をすべて</button>${choices}</div>`;root.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>{const level=Number(b.dataset.level);state.subPath=level<0?[]:state.subPath.slice(0,level+1);renderSubs();renderResults()});root.querySelectorAll('[data-name]').forEach(b=>b.onclick=()=>{state.subPath.push(b.dataset.name);renderSubs();renderResults()})}
function selectedNode(){let nodes=hierarchy[state.category]||[],node=null;for(const name of state.subPath){node=nodes.find(n=>n.name===name);nodes=node?.children||[]}return node}
function matches(shop,menu){const hay=normalize([shop.name,shop.area,menu.name,...menu.categories,...menu.tags].join(' '));const node=selectedNode();const favoriteMatch=(!state.shopFavoritesOnly&&!state.menuFavoritesOnly)||(state.shopFavoritesOnly&&state.shopFavorites.has(shop.id))||(state.menuFavoritesOnly&&state.menuFavorites.has(menu.id));return(!state.q||hay.includes(normalize(state.q)))&&(!state.category||menu.categories.includes(state.category))&&(!state.area||shop.area===state.area)&&(!node||node.match.test(menu.name))&&favoriteMatch}
function rows(){let items=state.data.flatMap(shop=>shop.menus.filter(m=>matches(shop,m)).map(menu=>({shop,menu,dist:state.position&&shop.lat!=null?distance(state.position,shop):null})));items.sort(state.sort==='distance'?(a,b)=>(a.dist??Infinity)-(b.dist??Infinity)||(a.shop.name.localeCompare(b.shop.name,'ja')):(a,b)=>a.shop.name.localeCompare(b.shop.name,'ja')||b.menu.special-a.menu.special);return items}
function renderResults(){updateUrl();const items=rows();$('#result-count').textContent=items.length;$('#status').hidden=true;const root=$('#cards');root.innerHTML='';if(!items.length){root.innerHTML='<div class="empty"><b>見つかりませんでした</b><br>条件を減らすか、別の言葉で試してください。</div>';return}const tpl=$('#card-template');items.forEach(({shop,menu,dist})=>{const card=tpl.content.firstElementChild.cloneNode(true);card.classList.toggle('is-special',menu.special);const img=card.querySelector('.photo');img.src=shop.imageUrl;img.alt=`${shop.name} ${menu.name}`;img.onerror=()=>img.remove();card.querySelector('.area').textContent=shop.area;card.querySelector('.menu-name').textContent=menu.name;card.querySelector('.shop-name').textContent=shop.name;card.querySelector('.chips').innerHTML=[...menu.categories,...menu.tags].map(x=>`<span class="chip">${x}</span>`).join('');card.querySelector('.distance').textContent=formatDistance(dist);card.querySelector('.card-main').onclick=()=>openDetail(shop,menu,dist);const shopFav=card.querySelector('.shop-favorite'),menuFav=card.querySelector('.menu-favorite');setFavoriteButton(shopFav,state.shopFavorites.has(shop.id),'店');setFavoriteButton(menuFav,state.menuFavorites.has(menu.id),'飯');shopFav.onclick=()=>toggleShopFavorite(shop.id);menuFav.onclick=()=>toggleMenuFavorite(menu.id);card.querySelector('.map-direct').onclick=()=>openMap(shop);root.append(card)})}
function setFavoriteButton(button,on,label){button.classList.toggle('on',on);button.textContent=on?`${label}♥`:`${label}♡`;button.setAttribute('aria-label',`${label==='店'?'お店':'メニュー'}をお気に入り${on?'から削除':'に追加'}`)}
function toggleShopFavorite(id){state.shopFavorites.has(id)?state.shopFavorites.delete(id):state.shopFavorites.add(id);localStorage.setItem('rsr-shop-favorites',JSON.stringify([...state.shopFavorites]));renderResults()}
function toggleMenuFavorite(id){state.menuFavorites.has(id)?state.menuFavorites.delete(id):state.menuFavorites.add(id);localStorage.setItem('rsr-menu-favorites',JSON.stringify([...state.menuFavorites]));renderResults()}
function openDetail(shop,menu,dist){const menus=shop.menus.map(m=>`<li>${m.special?'<b>RSRスペシャル：</b>':''}${m.name}</li>`).join('');$('#detail-content').innerHTML=`<button class="detail-close" aria-label="閉じる">×</button><img class="detail-image" src="${shop.imageUrl}" alt="${shop.name}"><div class="detail-inner"><div class="area">${shop.area}</div><h2>${shop.name}</h2><button class="place-button" type="button">⌖ ${shop.area}を地図で見る</button><div class="distance">${formatDistance(dist)}</div>${shop.coordinateType==='estimated-area-center'?'<p class="coordinate-note">公式会場マップを基準にした出店エリア中心までの概算です。店舗テント個別の測量座標ではありません。</p>':''}<h3>選んだメニュー</h3><p><b>${menu.name}</b></p><div class="chips">${[...menu.categories,...menu.tags].map(x=>`<span class="chip">${x}</span>`).join('')}</div><div class="detail-favorite-actions"><button class="detail-shop-fav">${state.shopFavorites.has(shop.id)?'店♥ お店お気に入り済み':'店♡ お店をお気に入り'}</button><button class="detail-menu-fav">${state.menuFavorites.has(menu.id)?'飯♥ メニューお気に入り済み':'飯♡ メニューをお気に入り'}</button></div><h3>全メニュー</h3><ul class="menu-list">${menus}</ul>${shop.description?`<h3>店舗PR</h3><p>${shop.description}</p>`:''}<div class="detail-actions"><a href="${shop.sourceUrl}" target="_blank" rel="noopener">公式情報を見る ↗</a></div></div>`;$('#detail-content .detail-close').onclick=()=>$('#detail').close();$('#detail-content .place-button').onclick=()=>{$('#detail').close();openMap(shop)};$('#detail-content .detail-shop-fav').onclick=()=>{toggleShopFavorite(shop.id);$('#detail').close()};$('#detail-content .detail-menu-fav').onclick=()=>{toggleMenuFavorite(menu.id);$('#detail').close()};$('#detail').showModal()}
function locationIcon(kind){const shop=kind==='shop';return L.divIcon({className:`map-pin ${kind}`,html:shop?'<div class="pin-label">この店</div><span><b>店</b></span><i></i>':'<span><b>●</b></span>',iconSize:shop?[74,58]:[38,46],iconAnchor:shop?[37,54]:[19,42]})}
function toVenuePoint(lat,lng){return{x:venueMap.x[0]*lat+venueMap.x[1]*lng+venueMap.x[2],y:venueMap.y[0]*lat+venueMap.y[1]*lng+venueMap.y[2]}}
function pointInVenue(p){return p.x>=0&&p.x<=venueMap.width&&p.y>=0&&p.y<=venueMap.height}
function venueLatLng(point){return[venueMap.height-point.y,point.x]}
function addUserToMap(){if(!state.map||!state.position)return;if(state.userLayer)state.userLayer.remove();const user=toVenuePoint(state.position.lat,state.position.lng);if(!pointInVenue(user)){$('#map-locate').textContent='現在地は会場マップ範囲外です';return}state.userLayer=L.layerGroup([L.marker(venueLatLng(user),{icon:locationIcon('user'),title:'現在地'}).bindPopup('現在地'),L.circle(venueLatLng(user),{radius:Math.max(10,(state.position.accuracy||20)*1.2),color:'#2276d2',fillColor:'#5aa8ff',fillOpacity:.12,weight:1})]).addTo(state.map);$('#map-locate').textContent='✓ 現在地を表示中'}
function openMap(shop){state.mapShop=shop;$('#map-shop-name').textContent=shop.name;$('#map-area-name').textContent=shop.area;$('#map-locate').textContent=state.position?'✓ 現在地を表示中':'◎ 現在地も表示';$('#map-dialog').showModal();setTimeout(()=>{if(state.map)state.map.remove();const bounds=[[0,0],[venueMap.height,venueMap.width]],manual=venueAreaPoints[shop.area],point=manual||toVenuePoint(shop.lat,shop.lng);state.map=L.map('shop-map',{crs:L.CRS.Simple,zoomControl:true,minZoom:-2,maxZoom:2,zoomSnap:.25,maxBounds:L.latLngBounds(bounds).pad(.18)});L.imageOverlay('assets/map2026_2.jpg',bounds,{alt:'RSR2026公式会場マップ'}).addTo(state.map);L.marker(venueLatLng(point),{icon:locationIcon('shop'),title:shop.area}).addTo(state.map).bindPopup(`<b>${shop.area}</b><br>${shop.name}<br><small>${manual?'指定された出店位置':'推定エリア中心'}</small>`);state.map.fitBounds(bounds,{padding:[8,8]});addUserToMap();},100)}
function locate(onSuccess){if(!navigator.geolocation){alert('この端末では位置情報を利用できません。');return}$('#locate').textContent='位置を確認中…';$('#map-locate').textContent='位置を確認中…';navigator.geolocation.getCurrentPosition(p=>{state.position={lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy};$('#locate').textContent='✓ 現在地を取得済み';$('#map-locate').textContent='✓ 現在地を表示中';state.sort='distance';$('#sort').value='distance';showNearestArea();renderResults();addUserToMap();if(typeof onSuccess==='function')onSuccess()},()=>{$('#locate').textContent='◎ 現在地を使う';$('#map-locate').textContent='◎ 現在地も表示';alert('位置情報を取得できませんでした。検索と地図はそのまま利用できます。')},{enableHighAccuracy:true,timeout:10000,maximumAge:60000})}
function render(){renderCategories();renderResults()}
$('#search').oninput=e=>{state.q=e.target.value;renderResults()};$('#clear-search').onclick=()=>{$('#search').value='';state.q='';renderResults();$('#search').focus()};$('#area-filter').onchange=e=>{state.area=e.target.value;renderResults()};$('#shop-favorites-only').onchange=e=>{state.shopFavoritesOnly=e.target.checked;renderResults()};$('#menu-favorites-only').onchange=e=>{state.menuFavoritesOnly=e.target.checked;renderResults()};$('#sort').onchange=e=>{state.sort=e.target.value;renderResults()};$('#locate').onclick=()=>locate();$('#map-locate').onclick=()=>locate();$('#detail').onclick=e=>{if(e.target===$('#detail'))$('#detail').close()};$('.map-close').onclick=()=>$('#map-dialog').close();$('#map-dialog').onclick=e=>{if(e.target===$('#map-dialog'))$('#map-dialog').close()};$('#map-dialog').addEventListener('close',()=>{if(state.map){state.map.remove();state.map=null}state.userLayer=null});
document.querySelectorAll('.bottom-nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.bottom-nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(b.dataset.action==='search'){state.shopFavoritesOnly=false;state.menuFavoritesOnly=false;$('#shop-favorites-only').checked=false;$('#menu-favorites-only').checked=false;scrollTo({top:0,behavior:'smooth'});renderResults()}if(b.dataset.action==='favorites'){state.shopFavoritesOnly=true;state.menuFavoritesOnly=true;$('#shop-favorites-only').checked=true;$('#menu-favorites-only').checked=true;renderResults();scrollTo({top:document.querySelector('.results').offsetTop,behavior:'smooth'})}if(b.dataset.action==='near')locate()});
fetch('data/shops.json').then(r=>{if(!r.ok)throw Error(r.status);return r.json()}).then(d=>{state.data=d.shops;renderAreas();render()}).catch(()=>{$('#status').textContent='データを読み込めませんでした。通信環境を確認して再読み込みしてください。'});
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('sw.js'));
