const state={data:[],q:'',category:'',sub:'',favorites:new Set(JSON.parse(localStorage.getItem('rsr-favorites')||'[]')),favoritesOnly:false,position:null,sort:'name'};
const $=s=>document.querySelector(s);const categories=['麺','ご飯','カレー','肉','海鮮','軽食','スイーツ','朝食','飲み物'];
const params=new URLSearchParams(location.search);state.q=params.get('q')||'';state.category=params.get('category')||'';state.favoritesOnly=params.get('favorites')==='1';
$('#search').value=state.q;$('#favorites-only').checked=state.favoritesOnly;

function normalize(s=''){return s.normalize('NFKC').toLowerCase().replace(/[ァ-ン]/g,c=>String.fromCharCode(c.charCodeAt(0)-0x60)).replace(/\s/g,'')}
function distance(a,b){const r=6371000,p=Math.PI/180,dLat=(b.lat-a.lat)*p,dLng=(b.lng-a.lng)*p;const x=Math.sin(dLat/2)**2+Math.cos(a.lat*p)*Math.cos(b.lat*p)*Math.sin(dLng/2)**2;return 2*r*Math.asin(Math.sqrt(x))}
function formatDistance(m){if(m==null)return '距離情報準備中';if(m<1000)return `現在地から 約${Math.round(m/10)*10}m`;return `現在地から 約${(m/1000).toFixed(1)}km`}
function updateUrl(){const p=new URLSearchParams();if(state.q)p.set('q',state.q);if(state.category)p.set('category',state.category);if(state.favoritesOnly)p.set('favorites','1');history.replaceState(null,'',`${location.pathname}${p.size?'?'+p:''}`)}
function renderCategories(){const root=$('#categories');root.innerHTML='';categories.forEach(c=>{const b=document.createElement('button');b.className='category'+(state.category===c?' selected':'');b.textContent=c;b.onclick=()=>{state.category=state.category===c?'':c;state.sub='';render();};root.append(b)});renderSubs()}
function renderSubs(){const root=$('#subfilters');if(!state.category){root.hidden=true;return}const subs=[...new Set(state.data.flatMap(s=>s.menus).filter(m=>m.categories.includes(state.category)).map(m=>m.name).filter(n=>n.length<14))].slice(0,12);root.hidden=!subs.length;root.innerHTML='<button data-sub="">すべて</button>'+subs.map(s=>`<button data-sub="${s.replaceAll('"','&quot;')}">${s}</button>`).join('');root.querySelectorAll('button').forEach(b=>{b.classList.toggle('selected',state.sub===b.dataset.sub);b.onclick=()=>{state.sub=b.dataset.sub;renderResults()}})}
function matches(shop,menu){const hay=normalize([shop.name,shop.area,menu.name,...menu.categories,...menu.tags].join(' '));return(!state.q||hay.includes(normalize(state.q)))&&(!state.category||menu.categories.includes(state.category))&&(!state.sub||menu.name===state.sub)&&(!state.favoritesOnly||state.favorites.has(shop.id))}
function rows(){let items=state.data.flatMap(shop=>shop.menus.filter(m=>matches(shop,m)).map(menu=>({shop,menu,dist:state.position&&shop.lat!=null?distance(state.position,shop):null})));items.sort(state.sort==='distance'?(a,b)=>(a.dist??Infinity)-(b.dist??Infinity)||(a.shop.name.localeCompare(b.shop.name,'ja')):(a,b)=>a.shop.name.localeCompare(b.shop.name,'ja')||b.menu.special-a.menu.special);return items}
function renderResults(){updateUrl();const items=rows();$('#result-count').textContent=items.length;$('#status').hidden=true;const root=$('#cards');root.innerHTML='';if(!items.length){root.innerHTML='<div class="empty"><b>見つかりませんでした</b><br>条件を減らすか、別の言葉で試してください。</div>';return}const tpl=$('#card-template');items.forEach(({shop,menu,dist})=>{const card=tpl.content.firstElementChild.cloneNode(true);card.classList.toggle('is-special',menu.special);const img=card.querySelector('.photo');img.src=shop.imageUrl;img.alt=`${shop.name} ${menu.name}`;img.onerror=()=>img.remove();card.querySelector('.area').textContent=shop.area;card.querySelector('.menu-name').textContent=menu.name;card.querySelector('.shop-name').textContent=shop.name;card.querySelector('.chips').innerHTML=[...menu.categories,...menu.tags].map(x=>`<span class="chip">${x}</span>`).join('');card.querySelector('.distance').textContent=formatDistance(dist);card.querySelector('.card-main').onclick=()=>openDetail(shop,menu,dist);const fav=card.querySelector('.favorite');fav.classList.toggle('on',state.favorites.has(shop.id));fav.textContent=state.favorites.has(shop.id)?'♥':'♡';fav.setAttribute('aria-label',state.favorites.has(shop.id)?'お気に入りから削除':'お気に入りに追加');fav.onclick=()=>toggleFavorite(shop.id);root.append(card)})}
function toggleFavorite(id){state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);localStorage.setItem('rsr-favorites',JSON.stringify([...state.favorites]));renderResults()}
function openDetail(shop,menu,dist){const menus=shop.menus.map(m=>`<li>${m.special?'<b>RSRスペシャル：</b>':''}${m.name}</li>`).join('');$('#detail-content').innerHTML=`<button class="detail-close" aria-label="閉じる">×</button><img class="detail-image" src="${shop.imageUrl}" alt="${shop.name}"><div class="detail-inner"><div class="area">${shop.area}</div><h2>${shop.name}</h2><div class="distance">${formatDistance(dist)}</div><h3>選んだメニュー</h3><p><b>${menu.name}</b></p><div class="chips">${[...menu.categories,...menu.tags].map(x=>`<span class="chip">${x}</span>`).join('')}</div><h3>全メニュー</h3><ul class="menu-list">${menus}</ul>${shop.description?`<h3>店舗PR</h3><p>${shop.description}</p>`:''}<div class="detail-actions"><a href="${shop.sourceUrl}" target="_blank" rel="noopener">公式情報を見る ↗</a><button class="detail-fav">${state.favorites.has(shop.id)?'♥ お気に入り済み':'♡ お気に入り'}</button></div></div>`;$('#detail-content .detail-close').onclick=()=>$('#detail').close();$('#detail-content .detail-fav').onclick=()=>{toggleFavorite(shop.id);$('#detail').close()};$('#detail').showModal()}
function locate(){if(!navigator.geolocation){alert('この端末では位置情報を利用できません。');return}$('#locate').textContent='位置を確認中…';navigator.geolocation.getCurrentPosition(p=>{state.position={lat:p.coords.latitude,lng:p.coords.longitude};$('#locate').textContent='✓ 現在地を取得済み';state.sort='distance';$('#sort').value='distance';renderResults()},()=>{$('#locate').textContent='◎ 現在地を使う';alert('位置情報を取得できませんでした。検索はそのまま利用できます。')},{enableHighAccuracy:true,timeout:10000,maximumAge:60000})}
function render(){renderCategories();renderResults()}
$('#search').oninput=e=>{state.q=e.target.value;renderResults()};$('#clear-search').onclick=()=>{$('#search').value='';state.q='';renderResults();$('#search').focus()};$('#favorites-only').onchange=e=>{state.favoritesOnly=e.target.checked;renderResults()};$('#sort').onchange=e=>{state.sort=e.target.value;renderResults()};$('#locate').onclick=locate;$('#detail').onclick=e=>{if(e.target===$('#detail'))$('#detail').close()};
document.querySelectorAll('.bottom-nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.bottom-nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(b.dataset.action==='search'){state.favoritesOnly=false;$('#favorites-only').checked=false;scrollTo({top:0,behavior:'smooth'});renderResults()}if(b.dataset.action==='favorites'){state.favoritesOnly=true;$('#favorites-only').checked=true;renderResults();scrollTo({top:document.querySelector('.results').offsetTop,behavior:'smooth'})}if(b.dataset.action==='near')locate()});
fetch('data/shops.json').then(r=>{if(!r.ok)throw Error(r.status);return r.json()}).then(d=>{state.data=d.shops;render()}).catch(()=>{$('#status').textContent='データを読み込めませんでした。通信環境を確認して再読み込みしてください。'});
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('sw.js'));
