import{createClient}from'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';

const config=window.IMAKOKO_CONFIG||{},configured=config.supabaseUrl?.startsWith('https://')&&!config.supabaseAnonKey?.startsWith('YOUR_');
const $=selector=>document.querySelector(selector),mapSize={width:2072,height:1910};
const venueMap={x:[514.8338934897748,87514.69744314403,-12385714.221532168],y:[151476.22812558583,-11664.858619111323,-4891383.699124284]};
const state={client:null,user:null,groupId:null,channel:null,pins:[],selected:null,draft:null,layers:null,watchId:null,lastAutoAt:0,lastAutoPoint:null,registering:false};
const map=L.map('map',{crs:L.CRS.Simple,minZoom:-2,maxZoom:2,zoomSnap:.25,maxBounds:L.latLngBounds([[0,0],[mapSize.height,mapSize.width]]).pad(.15)});
const bounds=[[0,0],[mapSize.height,mapSize.width]];L.imageOverlay('../assets/map2026_2.jpg',bounds).addTo(map);map.fitBounds(bounds,{padding:[6,6]});state.layers=L.layerGroup().addTo(map);
const resizeMap=()=>{map.invalidateSize();if(!state.pins.length)map.fitBounds(bounds,{padding:[6,6]})};
new ResizeObserver(()=>resizeMap()).observe($('#map'));addEventListener('orientationchange',()=>setTimeout(resizeMap,250));addEventListener('resize',()=>setTimeout(resizeMap,100));setTimeout(resizeMap,300);

const pointToLatLng=p=>[mapSize.height-p.y,p.x];
const latLngToPoint=ll=>({x:ll.lng,y:mapSize.height-ll.lat});
const gpsToPoint=(lat,lng)=>({x:venueMap.x[0]*lat+venueMap.x[1]*lng+venueMap.x[2],y:venueMap.y[0]*lat+venueMap.y[1]*lng+venueMap.y[2]});
const inside=p=>p.x>=0&&p.x<=mapSize.width&&p.y>=0&&p.y<=mapSize.height;
const name=()=>$('#display-name').value.trim();
const groupCode=()=>$('#group-code').value.trim().toUpperCase();
const time=iso=>new Intl.DateTimeFormat('ja-JP',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(iso));
const escapeHtml=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));

function selectPoint(point,label='地図で選択'){state.selected=point;if(state.draft)state.draft.remove();state.draft=L.marker(pointToLatLng(point),{icon:L.divIcon({className:'',html:'<div class="draft-pin"></div>',iconSize:[28,28],iconAnchor:[14,14]})}).addTo(map);$('#selection').textContent=`${label}しました。「今ここ」で登録できます`;$('#pin-now').disabled=!name()}
map.on('click',event=>selectPoint(latLngToPoint(event.latlng)));

function personColor(person){const colors=['#e34a33','#2477c9','#7a4bc2','#11856f','#d06b16','#c43b78','#3b7d23','#8a5b22','#087f9c','#6d607e'];let hash=0;for(const char of person)hash=(hash*31+char.codePointAt(0))>>>0;return colors[hash%colors.length]}
function markerIcon(person,latest,createdAt){const initial=[...person][0]||'●',clock=new Intl.DateTimeFormat('ja-JP',{hour:'2-digit',minute:'2-digit'}).format(new Date(createdAt)),color=personColor(person);return L.divIcon({className:'pin-wrap',html:`<div class="map-pin ${latest?'latest':'past-pin'}" style="--person-color:${color}"><span>${escapeHtml(initial)}</span></div><div class="pin-time" style="--person-color:${color}">${clock}</div>`,iconSize:[72,58],iconAnchor:[latest?21:17,latest?40:32]})}
function render(){state.layers.clearLayers();const grouped=new Map;state.pins.forEach(pin=>{if(!grouped.has(pin.display_name))grouped.set(pin.display_name,[]);grouped.get(pin.display_name).push(pin)});const root=$('#people');root.innerHTML='';$('#empty').hidden=state.pins.length>0;for(const[person,pins]of grouped){pins.sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));pins.forEach((pin,index)=>L.marker(pointToLatLng(pin),{icon:markerIcon(person,index===0,pin.created_at),zIndexOffset:index===0?500:0}).addTo(state.layers).bindPopup(`<b>${escapeHtml(person)}</b><br><b>登録時刻：${time(pin.created_at)}</b>${index===0?'<br><strong>最新の場所</strong>':''}`));const card=document.createElement('article');card.className='person';card.innerHTML=`<div class="person-head"><b>${escapeHtml(person)}</b><small>${pins.length}/5本</small></div><div class="history">${pins.map((pin,index)=>`<button data-id="${pin.id}">${index===0?'今ここ ':''}${time(pin.created_at)}</button>`).join('')}</div>`;card.querySelectorAll('button').forEach(button=>button.onclick=()=>{const pin=pins.find(p=>p.id===button.dataset.id);map.flyTo(pointToLatLng(pin),.5);state.layers.eachLayer(layer=>{const ll=layer.getLatLng?.();if(ll&&Math.abs(ll.lng-pin.x)<1&&Math.abs((mapSize.height-ll.lat)-pin.y)<1)layer.openPopup()})});root.append(card)}}

async function load(){if(!state.groupId){state.pins=[];render();return}const{data,error}=await state.client.from('location_pins').select('*').eq('group_id',state.groupId).order('created_at',{ascending:false});if(error)throw error;state.pins=data;render();$('#connection').textContent='● グループ共有中';$('#connection').className='connection ok'}
async function activateGroup(groupId,code,memberName=''){if(state.watchId!=null)stopAutoShare();state.groupId=groupId;$('#group-select').value=groupId;$('#display-name').value=memberName||'';localStorage.setItem('imakoko-group-id',groupId);$('#group-status').textContent=`「${code}」で使う名前を設定できます`;$('#group-status').className='group-status joined';if(state.channel)await state.client.removeChannel(state.channel);state.channel=state.client.channel(`location-pins-${groupId}`).on('postgres_changes',{event:'*',schema:'public',table:'location_pins',filter:`group_id=eq.${groupId}`},load).subscribe();await load();resizeMap()}
async function loadGroups(preferredId=localStorage.getItem('imakoko-group-id')){const{data,error}=await state.client.rpc('my_location_groups_with_names');if(error)throw error;const select=$('#group-select');select.innerHTML='<option value="">参加中のグループを選択</option>'+data.map(group=>`<option value="${group.group_id}" data-name="${escapeHtml(group.member_name||'')}">${escapeHtml(group.group_code)}</option>`).join('');const selected=data.find(group=>group.group_id===preferredId);if(selected)await activateGroup(selected.group_id,selected.group_code,selected.member_name);else if(data.length===1)await activateGroup(data[0].group_id,data[0].group_code,data[0].member_name);else{state.groupId=null;state.pins=[];render();$('#connection').textContent=data.length?'グループを選択':'グループ未参加'}}
async function joinGroup(){if(!groupCode()){alert('新しいグループコードを入力してください');return}$('#join-group').disabled=true;try{const code=groupCode(),{data,error}=await state.client.rpc('join_location_group',{input_code:code,input_name:name()||null});if(error)throw error;$('#group-code').value='';await loadGroups(data);await activateGroup(data,code)}catch(error){alert(`グループに参加できませんでした：${error.message}`)}finally{$('#join-group').disabled=false}}
async function saveMemberName(){if(!state.groupId||!name())return;const{error}=await state.client.rpc('update_location_member_name',{input_group:state.groupId,input_name:name()});if(error)throw error}
async function register(options={}){if(state.registering)return false;if(!state.groupId){if(!options.silent)alert('先にグループコードを入力して参加してください');return false}if(!name()){if(!options.silent)alert('名前を入力してください');return false}if(!state.selected){if(!options.silent)alert('現在地を取得するか、地図をタップしてください');return false}state.registering=true;$('#pin-now').disabled=true;try{const registeredPoint={...state.selected};localStorage.setItem('imakoko-name',name());await saveMemberName();const{error}=await state.client.from('location_pins').insert({group_id:state.groupId,display_name:name(),x:Math.round(registeredPoint.x*10)/10,y:Math.round(registeredPoint.y*10)/10});if(error)throw error;state.lastAutoAt=Date.now();state.lastAutoPoint=registeredPoint;state.selected=null;if(state.draft){state.draft.remove();state.draft=null}$('#selection').textContent=`${options.auto?'自動共有':'現在地'}を登録しました`;await load();return true}catch(error){if(!options.silent)alert(`登録できませんでした：${error.message}`);return false}finally{state.registering=false;$('#pin-now').disabled=!state.selected||!name()||!state.groupId}}

$('#display-name').value='';$('#display-name').oninput=()=>$('#pin-now').disabled=!state.selected||!name()||!state.groupId;$('#save-name').onclick=async()=>{if(!name())return;try{await saveMemberName();$('#group-select').selectedOptions[0].dataset.name=name();$('#selection').textContent='このグループで使う名前を保存しました'}catch(error){alert(`名前を保存できませんでした：${error.message}`)}};$('#join-group').onclick=joinGroup;$('#group-select').onchange=async event=>{if(!event.target.value)return;const option=event.target.selectedOptions[0];await activateGroup(event.target.value,option.textContent,option.dataset.name||'')};$('#pin-now').onclick=register;$('#refresh').onclick=load;

async function loadAdmin(){const password=$('#admin-password').value;if(!password){alert('管理パスワードを入力してください');return}$('#admin-load').disabled=true;try{const{data,error}=await state.client.rpc('admin_location_groups',{input_password:password});if(error)throw error;const root=$('#admin-groups');root.innerHTML='';for(const group of data){const{data:members,error:memberError}=await state.client.rpc('admin_location_group_members',{input_password:password,input_group:group.group_id});if(memberError)throw memberError;const card=document.createElement('article');card.className='admin-group';card.innerHTML=`<div class="admin-group-head"><div><b>${escapeHtml(group.group_code)}</b><br><small>登録者 ${group.member_count}人・ピン ${group.pin_count}本</small></div><button type="button">削除</button></div><ul class="admin-members">${members.length?members.map(member=>`<li>${escapeHtml(member.display_name||'名前未登録')}（ピン ${member.pin_count}本・参加 ${time(member.joined_at)}）</li>`).join(''):'<li>登録者なし</li>'}</ul>`;card.querySelector('button').onclick=async()=>{if(!confirm(`グループ「${group.group_code}」と全ピンを削除しますか？`))return;const{error:deleteError}=await state.client.rpc('admin_delete_location_group',{input_password:password,input_group:group.group_id});if(deleteError)return alert(`削除できませんでした：${deleteError.message}`);await loadAdmin()};root.append(card)}if(!data.length)root.innerHTML='<p class="empty">グループはまだありません。</p>'}catch(error){alert(`管理情報を取得できません：${error.message}`)}finally{$('#admin-load').disabled=false}}
$('#admin-open').onclick=()=>$('#admin-dialog').showModal();$('#admin-close').onclick=()=>$('#admin-dialog').close();$('#admin-load').onclick=loadAdmin;$('#admin-dialog').onclick=event=>{if(event.target===$('#admin-dialog'))$('#admin-dialog').close()};
function pointDistance(a,b){return a&&b?Math.hypot(a.x-b.x,a.y-b.y)*.8:Infinity}
async function usePosition(position,auto=false){const point=gpsToPoint(position.coords.latitude,position.coords.longitude);if(!inside(point)){if(!auto)alert('現在地は会場マップの範囲外です');return}if(auto&&Date.now()-state.lastAutoAt<300000&&pointDistance(point,state.lastAutoPoint)<50)return;selectPoint(point,auto?'自動取得':'現在地を取得');if(!auto)map.flyTo(pointToLatLng(point),.5);await register({auto,silent:auto})}
$('#locate').onclick=()=>{if(!navigator.geolocation)return alert('この端末では現在地を取得できません');if(!state.groupId||!name())return alert('先にグループを選び、名前を入力してください');$('#locate').textContent='取得・登録中…';navigator.geolocation.getCurrentPosition(async position=>{await usePosition(position);$('#locate').textContent='◎ 現在地を取得して登録'},()=>{$('#locate').textContent='◎ 現在地を取得して登録';alert('現在地を取得できませんでした')},{enableHighAccuracy:true,timeout:10000,maximumAge:30000})};
function stopAutoShare(){if(state.watchId!=null)navigator.geolocation.clearWatch(state.watchId);state.watchId=null;$('#auto-share').checked=false;$('#selection').textContent='自動共有を停止しました'}
$('#auto-share').onchange=event=>{if(!event.target.checked)return stopAutoShare();if(!navigator.geolocation){event.target.checked=false;return alert('この端末では現在地を取得できません')}if(!state.groupId||!name()){event.target.checked=false;return alert('先にグループを選び、名前を入力してください')}state.watchId=navigator.geolocation.watchPosition(position=>usePosition(position,true),()=>{stopAutoShare();alert('自動共有の位置情報を取得できませんでした')},{enableHighAccuracy:true,timeout:20000,maximumAge:60000});$('#selection').textContent='自動共有中です'};

async function start(){if(!configured){$('#connection').textContent='設定待ち';$('#connection').className='connection error';$('#setup-dialog').showModal();return}try{state.client=createClient(config.supabaseUrl,config.supabaseAnonKey);let{data:{session}}=await state.client.auth.getSession();if(!session){const{data,error}=await state.client.auth.signInAnonymously();if(error)throw error;session=data.session}state.user=session.user;$('#connection').textContent='グループを確認中';await loadGroups()}catch(error){$('#connection').textContent='接続エラー';$('#connection').className='connection error';alert(`共有サーバーに接続できません：${error.message}`)}}
start();
